### ISSUE TITLE
Package require Ruby 2.3.0

### ISSUE THREAD

**Issue by henryx** [fpm-within-docker/fpm-within-docker#8]
When I build the image for CentOS 7, I receive this error:
```
[...]
Step 4/5 : RUN gem install --no-ri --no-rdoc fpm -v 1.9.3
 ---> Running in cb20c8077322
Successfully installed cabin-0.9.0
Successfully installed backports-3.11.4
Successfully installed arr-pm-0.0.10
Successfully installed clamp-1.0.1
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
        ruby-xz requires Ruby version >= 2.3.0.
Successfully installed ffi-1.10.0
Successfully installed childprocess-0.9.0
The command '/bin/sh -c gem install --no-ri --no-rdoc fpm -v 1.9.3' returned a non-zero code: 1
$
```

**Comment by alanfranz** [comment]
Hello @henryx , sorry for being late, I missed some notifications from GitHub.

I'm not sure what you were trying to do, were you rebuilding the image? You can use it straight off docker cloud.

Recently, I have updated fpm-within-docker and I have check that it builds correctly, this is the latest centos-7 build log: https://cloud.docker.com/repository/registry-1.docker.io/alanfranz/fpm-within-docker/builds/e588a9e8-8a72-44e9-8279-61098d1c5abd

If you need me again, reopen a new bug. Make sure you copy-paste what you're actually doing (e.g. ```docker build...```).
