### ISSUE TITLE
Rebuild with latest FPM (v1.13.1)

### ISSUE THREAD

**Issue by weakcamel** [fpm-within-docker/fpm-within-docker#9]
Hello,

First of all, thank you for providing this image, it's been very useful for all.

It's been a while since the latest image was build and I was wondering if there's a change
to get a fresh one, featuring the 1.13.1 version of FPM?

https://github.com/jordansissel/fpm/blob/master/CHANGELOG.rst

Thanks in advance.

**Comment by alanfranz** [comment]
Hello @weakcamel , thanks for your interest.

I'm trying to rebuild some images, but I'm currently encountering some issues with Docker for Mac, and there's an additional problem: bintray, which I used to host packages, was sunset earlier this year. I should take a look for new repository options.

Have you got any suggestion about such topic? Also, which distributions were you interested in?

**Comment by weakcamel** [comment]
> bintray, which I used to host packages, was sunset earlier this year. I should take a look for new repository options.

Which types of packages do you need to host?

Some may work with [Github Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages) and when it comes to Debian/Ubuntu, a [PPA on Launchpad](https://login.launchpad.net/+new_account)

> Also, which distributions were you interested in?

Ubuntu; Focal and Bionic.

**Comment by alanfranz** [comment]
> Which types of packages do you need to host?

RPM and DEB. They are not supported by GitHub Packages.

PPAs don't allow externally built packages; I would need to build a debian directory. Which would defeat the very purpose of fpm-within-docker .

**Comment by alanfranz** [comment]
I apologize, it's a lot of time since I last worked on this project; of course for this project I don't deliver RPM and DEB, but Docker images ^_^

I'll try updating it soon.

**Comment by alanfranz** [comment]
Hello @weakcamel , everything should be OK now. Reopen the issue if you encounter problems.

**Comment by weakcamel** [comment]
> I apologize, it's a lot of time since I last worked on this project; of course for this project I don't deliver RPM and DEB, but Docker images ^_^

Lol. I was wondering which packages you had in mind and assumed that perhaps there's some dependency in certain Dockerfiles which I missed and you need to host somewhere first. 

No worries at all and many, many thanks - much appreciated!

**Comment by weakcamel** [comment]
P.S. And generally - no, sadly I don't know any other free public repository for DEBs or RPMs; the best I could come up with is host the file as a project release and install it directly from URL (which is obviously not as good as a Yum or APT repo but hey hum).
